export const SET_LIST_BOX_OFFICE = "SET_LIST_BOX_OFFICE";
export const SET_BOOKING_SEATS_USER = "SET_BOOKING_SEATS_USER";
export const BOOK_TICKET = "BOOK_TICKET";
export const DELETE_LIST_SEAT_BOOKING = "DELETE_LIST_SEAT_BOOKING";
export const CHANGE_TAB_ACTIVE = "CHANGE_TAB_ACTIVE";
export const DISPLAY_SIDEBAR = "DISPLAY_SIDEBAR";
