export const GET_LIST_CINEMA_SHOW_TIMES = "GET_LIST_CINEMA_SHOW_TIMES";
export const GET_FILM_SHOW_TIMES = "GET_FILM_SHOW_TIMES";
export const GET_CINEMA_BRANCH = "GET_CINEMA_BRANCH";
export const GET_CINEMA_BRANCH_BY_FILM = "GET_CINEMA_BRANCH_BY_FILM";
export const GET_DATE_BY_CINEMA_BRANCH = "GET_DATE_BY_CINEMA_BRANCH";
export const GET_TIME_BY_DATE = "GET_TIME_BY_DATE";
