export const SET_LIST_COMMENTS = "SET_LIST_COMMENTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const SET_MODAL_VISIBLE = "SET_MODAL_VISIBLE";
export const SET_MODAL_INVISIBLE = "SET_MODAL_INVISIBLE";
export const SET_COMMENT_BY_ID = "SET_COMMENT_BY_ID";
