export const SET_LOGIN_ACTION = "SET_LOGIN_ACTION";
export const SET_REGISTER_ACTION = "SET_REGISTER_ACTION";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";
export const SET_CLEAR_LOGIN_ERROR_MESSAGE = "SET_CLEAR_LOGIN_ERROR_MESSAGE";
export const SET_CLEAR_REGISTER_ACTION = "SET_CLEAR_REGISTER_ACTION";
export const SET_CLEAR_REGISTER_ERROR_MESSAGE =
  "SET_CLEAR_REGISTER_ERROR_MESSAGE";
export const SET_LIST_USERS = "SET_LIST_USERS";
export const SET_TOTAL_CUSTOMER = "SET_TOTAL_CUSTOMER";
